/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../app/app.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/router/src/router_module';
import * as import6 from '../../app/app-routing.module';
import * as import7 from '@angular/common/src/localization';
import * as import8 from '@angular/core/src/application_init';
import * as import9 from '@angular/core/src/testability/testability';
import * as import10 from '@angular/core/src/application_ref';
import * as import11 from '@angular/core/src/linker/compiler';
import * as import12 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import13 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import14 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import15 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import16 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import17 from '@angular/core/src/animation/animation_queue';
import * as import18 from '@angular/core/src/linker/view_utils';
import * as import19 from '@angular/platform-browser/src/browser/title';
import * as import20 from '@angular/common/src/location/location';
import * as import21 from '@angular/router/src/url_tree';
import * as import22 from '@angular/router/src/router_outlet_map';
import * as import23 from '@angular/core/src/linker/system_js_ng_module_factory_loader';
import * as import24 from '@angular/router/src/router_preloader';
import * as import25 from '@angular/core/src/di/injector';
import * as import26 from './app.component.ngfactory';
import * as import27 from '@angular/core/src/application_tokens';
import * as import28 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import29 from '@angular/platform-browser/src/dom/events/key_events';
import * as import30 from '@angular/core/src/zone/ng_zone';
import * as import31 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import32 from '@angular/common/src/location/platform_location';
import * as import33 from '@angular/common/src/location/location_strategy';
import * as import34 from '@angular/router/src/url_handling_strategy';
import * as import35 from '@angular/router/src/route_reuse_strategy';
import * as import36 from '@angular/router/src/router';
import * as import37 from '@angular/core/src/console';
import * as import38 from '@angular/core/src/i18n/tokens';
import * as import39 from '@angular/core/src/error_handler';
import * as import40 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import41 from '@angular/platform-browser/src/dom/animation_driver';
import * as import42 from '@angular/core/src/render/api';
import * as import43 from '@angular/core/src/security';
import * as import44 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import45 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import46 from '@angular/core/src/linker/ng_module_factory_loader';
import * as import47 from '@angular/router/src/router_config_loader';
import * as import48 from '@angular/router/src/router_state';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _ROUTER_FORROOT_GUARD_3:any;
  _RouterModule_4:import5.RouterModule;
  _AppRoutingModule_5:import6.AppRoutingModule;
  _AppModule_6:import1.AppModule;
  __LOCALE_ID_7:any;
  __NgLocalization_8:import7.NgLocaleLocalization;
  _ErrorHandler_9:any;
  _ApplicationInitStatus_10:import8.ApplicationInitStatus;
  _Testability_11:import9.Testability;
  _ApplicationRef__12:import10.ApplicationRef_;
  __ApplicationRef_13:any;
  __Compiler_14:import11.Compiler;
  __APP_ID_15:any;
  __DOCUMENT_16:any;
  __HAMMER_GESTURE_CONFIG_17:import12.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_18:any[];
  __EventManager_19:import13.EventManager;
  __DomSharedStylesHost_20:import14.DomSharedStylesHost;
  __AnimationDriver_21:any;
  __DomRootRenderer_22:import15.DomRootRenderer_;
  __NgProbeToken_23:any[];
  __RootRenderer_24:any;
  __DomSanitizer_25:import16.DomSanitizerImpl;
  __Sanitizer_26:any;
  __AnimationQueue_27:import17.AnimationQueue;
  __ViewUtils_28:import18.ViewUtils;
  __IterableDiffers_29:any;
  __KeyValueDiffers_30:any;
  __SharedStylesHost_31:any;
  __Title_32:import19.Title;
  __ROUTER_CONFIGURATION_33:any;
  __LocationStrategy_34:any;
  __Location_35:import20.Location;
  __UrlSerializer_36:import21.DefaultUrlSerializer;
  __RouterOutletMap_37:import22.RouterOutletMap;
  __NgModuleFactoryLoader_38:import23.SystemJsNgModuleLoader;
  __ROUTES_39:any[];
  __Router_40:any;
  __ActivatedRoute_41:any;
  _NoPreloading_42:import24.NoPreloading;
  _PreloadingStrategy_43:any;
  _RouterPreloader_44:import24.RouterPreloader;
  __PreloadAllModules_45:import24.PreloadAllModules;
  __ROUTER_INITIALIZER_46:any;
  __APP_BOOTSTRAP_LISTENER_47:any[];
  constructor(parent:import25.Injector) {
    super(parent,[import26.AppComponentNgFactory],[import26.AppComponentNgFactory]);
  }
  get _LOCALE_ID_7():any {
    if ((this.__LOCALE_ID_7 == null)) { (this.__LOCALE_ID_7 = 'en-US'); }
    return this.__LOCALE_ID_7;
  }
  get _NgLocalization_8():import7.NgLocaleLocalization {
    if ((this.__NgLocalization_8 == null)) { (this.__NgLocalization_8 = new import7.NgLocaleLocalization(this._LOCALE_ID_7)); }
    return this.__NgLocalization_8;
  }
  get _ApplicationRef_13():any {
    if ((this.__ApplicationRef_13 == null)) { (this.__ApplicationRef_13 = this._ApplicationRef__12); }
    return this.__ApplicationRef_13;
  }
  get _Compiler_14():import11.Compiler {
    if ((this.__Compiler_14 == null)) { (this.__Compiler_14 = new import11.Compiler()); }
    return this.__Compiler_14;
  }
  get _APP_ID_15():any {
    if ((this.__APP_ID_15 == null)) { (this.__APP_ID_15 = import27._appIdRandomProviderFactory()); }
    return this.__APP_ID_15;
  }
  get _DOCUMENT_16():any {
    if ((this.__DOCUMENT_16 == null)) { (this.__DOCUMENT_16 = import4._document()); }
    return this.__DOCUMENT_16;
  }
  get _HAMMER_GESTURE_CONFIG_17():import12.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_17 == null)) { (this.__HAMMER_GESTURE_CONFIG_17 = new import12.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_17;
  }
  get _EVENT_MANAGER_PLUGINS_18():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_18 == null)) { (this.__EVENT_MANAGER_PLUGINS_18 = [
      new import28.DomEventsPlugin(),
      new import29.KeyEventsPlugin(),
      new import12.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_17)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_18;
  }
  get _EventManager_19():import13.EventManager {
    if ((this.__EventManager_19 == null)) { (this.__EventManager_19 = new import13.EventManager(this._EVENT_MANAGER_PLUGINS_18,this.parent.get(import30.NgZone))); }
    return this.__EventManager_19;
  }
  get _DomSharedStylesHost_20():import14.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_20 == null)) { (this.__DomSharedStylesHost_20 = new import14.DomSharedStylesHost(this._DOCUMENT_16)); }
    return this.__DomSharedStylesHost_20;
  }
  get _AnimationDriver_21():any {
    if ((this.__AnimationDriver_21 == null)) { (this.__AnimationDriver_21 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_21;
  }
  get _DomRootRenderer_22():import15.DomRootRenderer_ {
    if ((this.__DomRootRenderer_22 == null)) { (this.__DomRootRenderer_22 = new import15.DomRootRenderer_(this._DOCUMENT_16,this._EventManager_19,this._DomSharedStylesHost_20,this._AnimationDriver_21,this._APP_ID_15)); }
    return this.__DomRootRenderer_22;
  }
  get _NgProbeToken_23():any[] {
    if ((this.__NgProbeToken_23 == null)) { (this.__NgProbeToken_23 = [import5.routerNgProbeToken()]); }
    return this.__NgProbeToken_23;
  }
  get _RootRenderer_24():any {
    if ((this.__RootRenderer_24 == null)) { (this.__RootRenderer_24 = import31._createConditionalRootRenderer(this._DomRootRenderer_22,this.parent.get(import31.NgProbeToken,(null as any)),this._NgProbeToken_23)); }
    return this.__RootRenderer_24;
  }
  get _DomSanitizer_25():import16.DomSanitizerImpl {
    if ((this.__DomSanitizer_25 == null)) { (this.__DomSanitizer_25 = new import16.DomSanitizerImpl()); }
    return this.__DomSanitizer_25;
  }
  get _Sanitizer_26():any {
    if ((this.__Sanitizer_26 == null)) { (this.__Sanitizer_26 = this._DomSanitizer_25); }
    return this.__Sanitizer_26;
  }
  get _AnimationQueue_27():import17.AnimationQueue {
    if ((this.__AnimationQueue_27 == null)) { (this.__AnimationQueue_27 = new import17.AnimationQueue(this.parent.get(import30.NgZone))); }
    return this.__AnimationQueue_27;
  }
  get _ViewUtils_28():import18.ViewUtils {
    if ((this.__ViewUtils_28 == null)) { (this.__ViewUtils_28 = new import18.ViewUtils(this._RootRenderer_24,this._Sanitizer_26,this._AnimationQueue_27)); }
    return this.__ViewUtils_28;
  }
  get _IterableDiffers_29():any {
    if ((this.__IterableDiffers_29 == null)) { (this.__IterableDiffers_29 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_29;
  }
  get _KeyValueDiffers_30():any {
    if ((this.__KeyValueDiffers_30 == null)) { (this.__KeyValueDiffers_30 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_30;
  }
  get _SharedStylesHost_31():any {
    if ((this.__SharedStylesHost_31 == null)) { (this.__SharedStylesHost_31 = this._DomSharedStylesHost_20); }
    return this.__SharedStylesHost_31;
  }
  get _Title_32():import19.Title {
    if ((this.__Title_32 == null)) { (this.__Title_32 = new import19.Title()); }
    return this.__Title_32;
  }
  get _ROUTER_CONFIGURATION_33():any {
    if ((this.__ROUTER_CONFIGURATION_33 == null)) { (this.__ROUTER_CONFIGURATION_33 = {useHash: true}); }
    return this.__ROUTER_CONFIGURATION_33;
  }
  get _LocationStrategy_34():any {
    if ((this.__LocationStrategy_34 == null)) { (this.__LocationStrategy_34 = import5.provideLocationStrategy(this.parent.get(import32.PlatformLocation),this.parent.get(import33.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_33)); }
    return this.__LocationStrategy_34;
  }
  get _Location_35():import20.Location {
    if ((this.__Location_35 == null)) { (this.__Location_35 = new import20.Location(this._LocationStrategy_34)); }
    return this.__Location_35;
  }
  get _UrlSerializer_36():import21.DefaultUrlSerializer {
    if ((this.__UrlSerializer_36 == null)) { (this.__UrlSerializer_36 = new import21.DefaultUrlSerializer()); }
    return this.__UrlSerializer_36;
  }
  get _RouterOutletMap_37():import22.RouterOutletMap {
    if ((this.__RouterOutletMap_37 == null)) { (this.__RouterOutletMap_37 = new import22.RouterOutletMap()); }
    return this.__RouterOutletMap_37;
  }
  get _NgModuleFactoryLoader_38():import23.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_38 == null)) { (this.__NgModuleFactoryLoader_38 = new import23.SystemJsNgModuleLoader(this._Compiler_14,this.parent.get(import23.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_38;
  }
  get _ROUTES_39():any[] {
      if ((this.__ROUTES_39 == null)) { (this.__ROUTES_39 = [[
        {
          path: 'one-page',
          loadChildren: 'app/one-page/one-page.module#OnePageModule'
        }
        ,
        {
          path: '',
          redirectTo: 'one-page',
          pathMatch: 'full'
        }

      ]
    ]); }
    return this.__ROUTES_39;
  }
  get _Router_40():any {
    if ((this.__Router_40 == null)) { (this.__Router_40 = import5.setupRouter(this._ApplicationRef_13,this._UrlSerializer_36,this._RouterOutletMap_37,this._Location_35,this,this._NgModuleFactoryLoader_38,this._Compiler_14,this._ROUTES_39,this._ROUTER_CONFIGURATION_33,this.parent.get(import34.UrlHandlingStrategy,(null as any)),this.parent.get(import35.RouteReuseStrategy,(null as any)))); }
    return this.__Router_40;
  }
  get _ActivatedRoute_41():any {
    if ((this.__ActivatedRoute_41 == null)) { (this.__ActivatedRoute_41 = import5.rootRoute(this._Router_40)); }
    return this.__ActivatedRoute_41;
  }
  get _PreloadAllModules_45():import24.PreloadAllModules {
    if ((this.__PreloadAllModules_45 == null)) { (this.__PreloadAllModules_45 = new import24.PreloadAllModules()); }
    return this.__PreloadAllModules_45;
  }
  get _ROUTER_INITIALIZER_46():any {
    if ((this.__ROUTER_INITIALIZER_46 == null)) { (this.__ROUTER_INITIALIZER_46 = import5.initialRouterNavigation(this._Router_40,this._ApplicationRef_13,this._RouterPreloader_44,this._ROUTER_CONFIGURATION_33)); }
    return this.__ROUTER_INITIALIZER_46;
  }
  get _APP_BOOTSTRAP_LISTENER_47():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_47 == null)) { (this.__APP_BOOTSTRAP_LISTENER_47 = [this._ROUTER_INITIALIZER_46]); }
    return this.__APP_BOOTSTRAP_LISTENER_47;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._ROUTER_FORROOT_GUARD_3 = import5.provideForRootGuard(this.parent.get(import36.Router,(null as any)));
    this._RouterModule_4 = new import5.RouterModule(this._ROUTER_FORROOT_GUARD_3);
    this._AppRoutingModule_5 = new import6.AppRoutingModule();
    this._AppModule_6 = new import1.AppModule();
    this._ErrorHandler_9 = import4.errorHandler();
    this._ApplicationInitStatus_10 = new import8.ApplicationInitStatus(this.parent.get(import8.APP_INITIALIZER,(null as any)));
    this._Testability_11 = new import9.Testability(this.parent.get(import30.NgZone));
    this._ApplicationRef__12 = new import10.ApplicationRef_(this.parent.get(import30.NgZone),this.parent.get(import37.Console),this,this._ErrorHandler_9,this,this._ApplicationInitStatus_10,this.parent.get(import9.TestabilityRegistry,(null as any)),this._Testability_11);
    this._NoPreloading_42 = new import24.NoPreloading();
    this._PreloadingStrategy_43 = this._NoPreloading_42;
    this._RouterPreloader_44 = new import24.RouterPreloader(this._Router_40,this._NgModuleFactoryLoader_38,this._Compiler_14,this,this._PreloadingStrategy_43);
    return this._AppModule_6;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.ROUTER_FORROOT_GUARD)) { return this._ROUTER_FORROOT_GUARD_3; }
    if ((token === import5.RouterModule)) { return this._RouterModule_4; }
    if ((token === import6.AppRoutingModule)) { return this._AppRoutingModule_5; }
    if ((token === import1.AppModule)) { return this._AppModule_6; }
    if ((token === import38.LOCALE_ID)) { return this._LOCALE_ID_7; }
    if ((token === import7.NgLocalization)) { return this._NgLocalization_8; }
    if ((token === import39.ErrorHandler)) { return this._ErrorHandler_9; }
    if ((token === import8.ApplicationInitStatus)) { return this._ApplicationInitStatus_10; }
    if ((token === import9.Testability)) { return this._Testability_11; }
    if ((token === import10.ApplicationRef_)) { return this._ApplicationRef__12; }
    if ((token === import10.ApplicationRef)) { return this._ApplicationRef_13; }
    if ((token === import11.Compiler)) { return this._Compiler_14; }
    if ((token === import27.APP_ID)) { return this._APP_ID_15; }
    if ((token === import40.DOCUMENT)) { return this._DOCUMENT_16; }
    if ((token === import12.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_17; }
    if ((token === import13.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_18; }
    if ((token === import13.EventManager)) { return this._EventManager_19; }
    if ((token === import14.DomSharedStylesHost)) { return this._DomSharedStylesHost_20; }
    if ((token === import41.AnimationDriver)) { return this._AnimationDriver_21; }
    if ((token === import15.DomRootRenderer)) { return this._DomRootRenderer_22; }
    if ((token === import10.NgProbeToken)) { return this._NgProbeToken_23; }
    if ((token === import42.RootRenderer)) { return this._RootRenderer_24; }
    if ((token === import16.DomSanitizer)) { return this._DomSanitizer_25; }
    if ((token === import43.Sanitizer)) { return this._Sanitizer_26; }
    if ((token === import17.AnimationQueue)) { return this._AnimationQueue_27; }
    if ((token === import18.ViewUtils)) { return this._ViewUtils_28; }
    if ((token === import44.IterableDiffers)) { return this._IterableDiffers_29; }
    if ((token === import45.KeyValueDiffers)) { return this._KeyValueDiffers_30; }
    if ((token === import14.SharedStylesHost)) { return this._SharedStylesHost_31; }
    if ((token === import19.Title)) { return this._Title_32; }
    if ((token === import5.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_33; }
    if ((token === import33.LocationStrategy)) { return this._LocationStrategy_34; }
    if ((token === import20.Location)) { return this._Location_35; }
    if ((token === import21.UrlSerializer)) { return this._UrlSerializer_36; }
    if ((token === import22.RouterOutletMap)) { return this._RouterOutletMap_37; }
    if ((token === import46.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_38; }
    if ((token === import47.ROUTES)) { return this._ROUTES_39; }
    if ((token === import36.Router)) { return this._Router_40; }
    if ((token === import48.ActivatedRoute)) { return this._ActivatedRoute_41; }
    if ((token === import24.NoPreloading)) { return this._NoPreloading_42; }
    if ((token === import24.PreloadingStrategy)) { return this._PreloadingStrategy_43; }
    if ((token === import24.RouterPreloader)) { return this._RouterPreloader_44; }
    if ((token === import24.PreloadAllModules)) { return this._PreloadAllModules_45; }
    if ((token === import5.ROUTER_INITIALIZER)) { return this._ROUTER_INITIALIZER_46; }
    if ((token === import27.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_47; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__12.ngOnDestroy();
    this._RouterPreloader_44.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);